version: "3.5"

networks:
  nw:
    name: my_network42
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp_volume
    driver_opts:
      type: none
      o: bind
      device: /home/ysay/data/wp
  db:
    driver: local
    name: db_volume
    driver_opts:
      type: none
      o: bind
      device: /home/ysay/data/db

services:
 
  mariadb_service:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - ./.env
    networks:
      - nw
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      
  wordpress_service:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - ./.env
    networks:
      - nw
    depends_on:
      - mariadb_service
    restart: unless-stopped
    volumes:
      - wp:/var/www/html

  nginx-server:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - ./.env
    ports:
      - "443:443"
    depends_on:
      - wordpress_service
    volumes:
      - wp:/var/www/html
    networks:
      - nw
    restart: unless-stopped

